parameters:

    sub_ccdn_message_message.component.bb_code.acl_integrator.class: SubCCDNMessage\MessageBundle\Component\BBCode\TagACLIntegrator

services:

    sub_ccdn_message_message.component.bb_code.acl_integrator:
        class: %sub_ccdn_message_message.component.bb_code.acl_integrator.class%
        arguments:
            - %sub_ccdn_message_message.bb_parser.acl%
        tags:
            - { name: ccdn_component_bb_code.acl }