imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ccdn/component-bb-code.yml }
    - { resource: ccdn/component-dashboard.yml }
    - { resource: ccdn/user-user.yml }
    - { resource: ccdn/user-profile.yml }
    - { resource: ccdn/user-admin.yml }
    - { resource: ccdn/forum-forum.yml }
    - { resource: ccdn/message-message.yml }
    # Sub CCDN Config Resources
    #- { resource: ccdn/sub/forum-forum.yml }
    #- { resource: ccdn/sub/message-message.yml }
    #- { resource: ccdn/sub/user-admin.yml }
    #- { resource: ccdn/sub/user-profile.yml }
    # Vendor Config Resources
    - { resource: vendor/assetic.yml }
    - { resource: vendor/knp-paginator.yml }
    - { resource: vendor/ewz-recaptcha.yml }
    - { resource: vendor/fos-user.yml }

framework:
    #esi:             ~
    translator:              { fallback: "%locale%" }
    secret:                  "%secret%"
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:                    true
    csrf_protection:         true
    validation:              { enable_annotations: true }
    templating:              
        engines:             ['twig']
        #assets_version: SomeVersionScheme
    default_locale:          "%locale%"
    trusted_hosts:           ~
    trusted_proxies:         ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:          session.handler.native_file
        save_path:           "%kernel.root_dir%/sessions"
    fragments:               ~
    http_method_override:    true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'CCDNComponentBBCodeBundle:Form:fields.html.twig'
            - 'EWZRecaptchaBundle:Form:ewz_recaptcha_widget.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        resolve_target_entities:
            'Symfony\Component\Security\Core\User\UserInterface': 'CCDNUser\UserBundle\Entity\User'
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    CCDNUserUserBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "Resources/config/doctrine"
                        alias:                ~
                        prefix:               CCDNUser\UserBundle\Entity
                        is_bundle:            true
                    CCDNUserProfileBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "Resources/config/doctrine"
                        alias:                ~
                        prefix:               CCDNUser\ProfileBundle\Entity
                        is_bundle:            true
                    CCDNUserSecurityBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "Resources/config/doctrine"
                        alias:                ~
                        prefix:               CCDNUser\SecurityBundle\Entity
                        is_bundle:            true
                    CCDNMessageMessageBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "Resources/config/doctrine"
                        alias:                ~
                        prefix:               CCDNMessage\MessageBundle\Entity
                        is_bundle:            true
                    CCDNForumForumBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "Resources/config/doctrine"
                        alias:                ~
                        prefix:               CCDNForum\ForumBundle\Entity
                        is_bundle:            true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

