imports:
    - { resource: config.yml }
    - { resource: ccdn/user-security.yml }

doctrine:
   dbal:
       dbname:   %database_name%_prod

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        grouped:
            type:         group
            members:      [streamed, buffered]
        streamed:
            type:         stream
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
        buffered:
            type:         buffer
            handler:      swift
        swift:
            type:         swift_mailer
            from_email:   error@codeconsortium.com
            to_email:     status@codeconsortium.com
            subject:      An Error Occurred!
            level:        debug
        nested:
            type:         stream
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
