imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        dbname:   %database_name%_test

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    spool:
        type: memory

# simulates authentication
# http://symfony.com/doc/current/cookbook/testing/http_authentication.html
security:
    firewalls:
        main:
            http_basic:
