imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# for fos_user_bundle
fos_user:
   db_driver:      orm
   firewall_name:  main
   user_class:     CCDNUser\UserBundle\Entity\User
   use_listener:   true
#    from_email:     { webmaster@example.com: Admin }
   profile:
       form:
#            type:               FOS\UserBundle\Form\ProfileFormType
#            handler:            FOS\UserBundle\Form\ProfileFormHandler
           name:               fos_user_profile_form
           validation_groups:  [Profile]
   change_password:
       form:
#            type:               FOS\UserBundle\Form\ChangePasswordFormType
#            handler:            FOS\UserBundle\Form\ChangePasswordFormHandler
#            name:               fos_user_change_password_form
#            validation_groups:  [ChangePassword]
   registration:
#        confirmation:
#            from_email: ~
#            enabled:    false
#            template:   FOSUserBundle:Registration:email.txt.twig
        form:
            type:               ccdn_user_registration
#            handler:            FOS\UserBundle\Form\RegistrationFormHandler
#            name:               fos_user_registration_form
#            validation_groups:  [Registration]
   resetting:
       token_ttl: 86400
#        email:
#            from_email: ~
#            template:   FOSUserBundle:Resetting:email.txt.twig
#        form:
#            type:               FOS\UserBundle\Form\ResettingFormType
#            handler:            FOS\UserBundle\Form\ResettingFormHandler
#            name:               fos_user_resetting_form
#            validation_groups:  [ResetPassword]
   service:
#        mailer:                 fos_user.util.mailer.default
 #      email_canonicalizer:    fos_user.util.email_canonicalizer.default
 #      username_canonicalizer: fos_user.util.username_canonicalizer.default
       user_manager:           fos_user.user_manager.default
#    encoder:
#        algorithm:          sha512
#        encode_as_base64:   false
#        iterations:         1
   template:
       engine: twig
       theme:  CCDNUserUserBundle:Form:fields.html.twig
#    group:
#        group_class:    ~ # Required when using groups
#        form:
#            type:               FOS\UserBundle\Form\GroupFormType
#            handler:            FOS\UserBundle\Form\GroupHandler
#            name:               fos_user_group_form
#            validation_groups:  [Registration]

# for CCDNUser MemberBundle
ccdn_user_member:
    user:
        profile_route: cc_profile_show_by_id
    members_per_page: 50
    template:
        engine: twig
        theme: CCDNUserMemberBundle:Form:fields.html.twig

ccdn_forum_forum:
    user:
        profile_route: cc_profile_show_by_id
    template:
        engine: twig
        theme: CCDNForumForumBundle:Form:fields.html.twig
    category:
        layout_templates:
            index: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    board:
        topics_per_page: 40
        layout_templates:
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    topic:
        posts_per_page: 10
        layout_templates:
            create: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            reply: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    post:
        layout_templates:
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            flag: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            edit_post: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            edit_topic: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            delete_post: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig

ccdn_forum_admin:
    user:
        profile_route: cc_profile_show_by_id
    template:
        engine: twig
        theme: CCDNForumForumAdminBundle:fields.html.twig
    category:
        layout_templates:
            create: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            delete_category: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            edit: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            index: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    board:
        topics_per_page: 40
        layout_templates:
            create: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            delete_board: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            edit: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig

ccdn_forum_moderator:
    user:
        profile_route: cc_profile_show_by_id
    template:
        engine: twig
        theme: CCDNForumForumModeratorBundle:fields.html.twig
    flag:
        flags_per_page: 40
        layout_templates:
            flag_mark: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show_flag: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show_flagged: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    topic:
        topics_per_page: 40
        posts_per_page: 20
        layout_templates:
            change_board: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show_closed: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            delete_topic: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    post:
        posts_per_page: 40
        layout_templates:
            show_locked: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig

ewz_recaptcha:
    public_key:   here_is_your_public_key
    private_key:  here_is_your_private_key
    secure:       false
    locale_key:   kernel.default_locale
    enabled: true

ccdn_message_message:
    user:
        profile_route: cc_profile_show_by_id
    template:
        engine: twig
        theme: CCDNMessageMessageBundle:Form:fields.html.twig
    folder:
        messages_per_page: 40
        layout_templates:
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    message:
        layout_templates:
            compose: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig

fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: %facebook_app_id%
    secret: %facebook_app_secret%
    cookie: true
    permissions: [email, user_birthday, user_location]

services:
    my.facebook.user:
        class: Acme\MyBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"