imports:
    - { resource: config.yml }
    - { resource: ccdn/user-security.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null
    #validation:
    #    cache: apc

doctrine:
    dbal:
        dbname:   %database_name%_prod
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        grouped:
            type:         group
            members:      [streamed, buffered]
        streamed:
            type:         stream
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
        buffered:
            type:         buffer
            handler:      swift
        swift:
            type:         swift_mailer
            from_email:   error@codeconsortium.com
            to_email:     status@codeconsortium.com
            subject:      An Error Occurred!
            level:        critical
        nested:
            type:         stream
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
        console:
            type:         console
