imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale:  %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'CCDNForumForumBundle:Form:fields.html.twig'
#            - 'CCDNComponentRecaptchaBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
        

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        #unix_socket: /Applications/MAMP/tmp/mysql/mysql.sock 
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
#    spool:     { type: memory }

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# for fos_user_bundle
fos_user:
   db_driver:      orm
   firewall_name:  main
   user_class:     CCDNUser\UserBundle\Entity\User
   use_listener:   true
#    from_email:     { webmaster@example.com: Admin }
   profile:
       form:
#            type:               FOS\UserBundle\Form\ProfileFormType
#            handler:            FOS\UserBundle\Form\ProfileFormHandler
           name:               fos_user_profile_form
           validation_groups:  [Profile]
   change_password:
       form:
#            type:               FOS\UserBundle\Form\ChangePasswordFormType
#            handler:            FOS\UserBundle\Form\ChangePasswordFormHandler
#            name:               fos_user_change_password_form
#            validation_groups:  [ChangePassword]
   registration:
#        confirmation:
#            from_email: ~
#            enabled:    false
#            template:   FOSUserBundle:Registration:email.txt.twig
        form:
            type:               ccdn_user_registration
#            handler:            FOS\UserBundle\Form\RegistrationFormHandler
#            name:               fos_user_registration_form
#            validation_groups:  [Registration]
   resetting:
       token_ttl: 86400
#        email:
#            from_email: ~
#            template:   FOSUserBundle:Resetting:email.txt.twig
#        form:
#            type:               FOS\UserBundle\Form\ResettingFormType
#            handler:            FOS\UserBundle\Form\ResettingFormHandler
#            name:               fos_user_resetting_form
#            validation_groups:  [ResetPassword]
   service:
#        mailer:                 fos_user.util.mailer.default
 #      email_canonicalizer:    fos_user.util.email_canonicalizer.default
 #      username_canonicalizer: fos_user.util.username_canonicalizer.default
       user_manager:           fos_user.user_manager.default
#    encoder:
#        algorithm:          sha512
#        encode_as_base64:   false
#        iterations:         1
   template:
       engine: twig
       theme:  CCDNUserUserBundle:Form:fields.html.twig
#    group:
#        group_class:    ~ # Required when using groups
#        form:
#            type:               FOS\UserBundle\Form\GroupFormType
#            handler:            FOS\UserBundle\Form\GroupHandler
#            name:               fos_user_group_form
#            validation_groups:  [Registration]


#
#
# FOS FACEBOOK
#
#
fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: %facebook_app_id%
    secret: %facebook_app_secret%
    cookie: true
    permissions: [email, user_birthday, user_location]
   
services:
    my.facebook.user:
        class: CCDNUser\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"



#
#
# EWZ Recatpcha bundle
#
#
ewz_recaptcha:
    public_key: %ewz_recaptcha_public_key%
    private_key: %ewz_recaptcha_private_key%
    secure: false
    locale_key: session.default_locale


              
#
#
#     CCDN
#
#


# for CCDNComponent AttachmentBundle
ccdn_component_attachment:
    user:
        profile_route: cc_profile_show_by_id
    template:
        engine: twig
        theme: CCDNComponentAttachmentBundle:Form:fields.html.twig
    store:
        dir: %ccdn_attachment_file_store%
    quota_per_user:
        max_files_quantity: 20
        max_filesize_per_file: 400KiB
        max_total_quota: 2000KiB
    attachment:
        layout_templates:
            list: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            upload: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig

# for CCDNUser MemberBundle    
ccdn_user_member:
    user:
        profile_route: cc_profile_show_by_id 
    members_per_page: 50       
    template:
        engine: twig
        theme: CCDNUserMemberBundle:Form:fields.html.twig
    member:
        layout_templates:
            list: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig

# for CCDNUser ProfileBundle
ccdn_user_profile:
    user:
        profile_route: cc_profile_show_by_id 
    template:
        engine: twig
        theme: CCDNUserProfileBundle:Form:fields.html.twig
    profile:
        layout_templates:
            edit: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
         
# for CCDNUser AdminBundle
ccdn_user_admin:
    user:
        profile_route: cc_profile_show_by_id 
    template:
        engine: twig
        theme: CCDNUserAdminBundle:Form:fields.html.twig
    activation:
        layout_templates:
            show_unactivated_users: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    ban:
        layout_templates:
            show_banned_users: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    role:
        layout_templates:
            set_users_role: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    account:
        layout_templates:
            edit_user: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show_newest_users: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show_user: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig

# for CCDNUser UserBundle   
ccdn_user_user:
    user:
        profile_route: cc_profile_show_by_id 
    template:
        engine: twig
        theme: CCDNUserUserBundle:Form:fields.html.twig
    account:
        layout_templates:
            edit: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig     
    password:
        layout_templates:
            change_password: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    registration:
        layout_templates:
            check_email: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            confirmed: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            register: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    resetting:
        layout_templates:
            check_email: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            password_already_requested: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            request: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            reset: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    security:
        layout_templates:
            login: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
        
# for CCDNMessage MessageBundle      
ccdn_message_message:  
    user:
        profile_route: cc_profile_show_by_id
    template:
        engine: twig
        theme: CCDNMessageMessageBundle:Form:fields.html.twig
    folder:
        messages_per_page: 10
        layout_templates:
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    message:
        layout_templates:
            compose: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    quotas:
        max_messages: 100

# for CCDNForum ForumBundle    
ccdn_forum_forum:
    user:
        profile_route: cc_profile_show_by_id
    template:
        engine: twig
        theme: CCDNForumForumBundle:Form:fields.html.twig
    category:
        layout_templates:
            index: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    board:
        topics_per_page: 4
        layout_templates:
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    topic:
        posts_per_page: 5
        layout_templates:
            create: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            reply: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    post:
        layout_templates:
            show: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            flag: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            edit_post: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            edit_topic: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            delete_post: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    draft:
        drafts_per_page: 2
        layout_templates:
            list: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig


ccdn_forum_admin:
    user:
        profile_route: cc_profile_show_by_id
    template:
        engine: twig
        theme: CCDNForumAdminBundle:Form:fields.html.twig
    category:
        layout_templates:
            create: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            delete_category: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            edit: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            index: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    board:
        topics_per_page: 40
        layout_templates:
            create: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            delete_board: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            edit: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig

ccdn_forum_moderator:
    user:
        profile_route: cc_profile_show_by_id
    template:
        engine: twig
        theme: CCDNForumModeratorBundle:Form:fields.html.twig
    flag:
        flags_per_page: 40
        layout_templates:
            flag_mark: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show_flag: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show_flagged: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    topic:
        topics_per_page: 40
        posts_per_page: 20
        layout_templates:
            change_board: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            show_closed: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
            delete_topic: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig
    post:
        posts_per_page: 40
        layout_templates:
            show_locked: CCDNComponentCommonBundle:Layout:layout_body_left.html.twig

