imports:
    - { resource: config.yml}
    - { resource: ccdn/user-security.yml }

doctrine:
   dbal:
       dbname:   %database_name%_test

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

swiftmailer:
    disable_delivery: true
    spool:
        type: memory

web_profiler_extra:
    routing:
        enabled:        false
        display_in_wdt: false
    container:
        enabled:        false
        display_in_wdt: false
    assetic:
        enabled:        false
        display_in_wdt: false
    twig:
        enabled:        false
        display_in_wdt: false

# simulates authentication
# http://symfony.com/doc/current/cookbook/testing/http_authentication.html
security:
    firewalls:
        main:
            http_basic:

#imports:
#    - { resource: config_dev.yml }
#
#doctrine:
#    dbal:
#        dbname:   %database_name%_test
#
#framework:
#    test: ~
#    session:
#        storage_id: session.storage.mock_file
#
#web_profiler:
#    toolbar: false
#    intercept_redirects: false
#
#
#swiftmailer:
#    disable_delivery: true
#    spool:
#        type: memory
#
## simulates authentication
## http://symfony.com/doc/current/cookbook/testing/http_authentication.html
#security:
#    firewalls:
#        main:
#            http_basic:
#
#
#
#
#