imports:
    - { resource: config_dev.yml }
    - { resource: ccdn/user-security.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:
        collect: false
        enabled: false
        only_exceptions: false

doctrine:
   dbal:
       dbname:   %database_name%_test

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    spool:
        type: memory

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

web_profiler_extra:
    routing:
        enabled:        false
        display_in_wdt: false
    container:
        enabled:        false
        display_in_wdt: false
    assetic:
        enabled:        false
        display_in_wdt: false
    twig:
        enabled:        false
        display_in_wdt: false

# simulates authentication
# http://symfony.com/doc/current/cookbook/testing/http_authentication.html
security:
    firewalls:
        main:
            http_basic: