_security_check:
      pattern:  /login_check/
_security_logout:
    pattern:  /logout
#
#_facebook_secured:
#        pattern: /secured/
#        defaults: { _controller: CCDNForumForumBundle:Category:index, _locale: en }
#

# CCDNComponent bundles
CCDNComponentAttachmentBundle:
    resource: "@CCDNComponentAttachmentBundle/Resources/config/routing.yml"
    prefix: /

# CCDNUser bundles
CCDNUserMemberBundle:
    resource: "@CCDNUserMemberBundle/Resources/config/routing.yml"
    prefix: /

CCDNUserProfileBundle:
    resource: "@CCDNUserProfileBundle/Resources/config/routing.yml"
    prefix: /

CCDNUserUserAdminBundle:
    resource: "@CCDNUserUserAdminBundle/Resources/config/routing.yml"
    prefix: /

CCDNUserUserBundle:
    resource: "@CCDNUserUserBundle/Resources/config/routing.yml"
    prefix: /

# CCDNForum bundles
CCDNForumModeratorBundle:
    resource: "@CCDNForumModeratorBundle/Resources/config/routing.yml"
    prefix: /

CCDNForumAdminBundle:
    resource: "@CCDNForumAdminBundle/Resources/config/routing.yml"
    prefix: /

CCDNForumForumBundle:
    resource: "@CCDNForumForumBundle/Resources/config/routing.yml"
    prefix: /

# CCDNMessage bundles
CCDNMessageMessageBundle:
    resource: "@CCDNMessageMessageBundle/Resources/config/routing.yml"
    prefix:   /
    
    
    
    
    
    
    
    
#login:
#    pattern:    /login
#    defaults:   { _controller: CCDNUserUserBundle:User:login }
#
#login_check:
#    pattern:    /login_check
#
#logout:
#    pattern:    /logout
#    defaults:   { _controller: CCDNUserUserBundle:User:logout }
#


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal