# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_security_check:
      pattern:  /login_check/
_security_logout:
    pattern:  /logout

_facebook_login_check:
      pattern:  /login_check/facebook
#
#_facebook_secured:
#        pattern: /secured/
#        defaults: { _controller: CCDNForumForumBundle:Category:index, _locale: en }
#

# CCDNComponent bundles
CCDNComponentCommonBundle:
    resource: "@CCDNComponentCommonBundle/Resources/config/routing.yml"
    prefix: /

CCDNComponentAttachmentBundle:
    resource: "@CCDNComponentAttachmentBundle/Resources/config/routing.yml"
    prefix: /

CCDNComponentDashboardBundle:
    resource: "@CCDNComponentDashboardBundle/Resources/config/routing.yml"
    prefix: /

# CCDNUser bundles
CCDNUserMemberBundle:
    resource: "@CCDNUserMemberBundle/Resources/config/routing.yml"
    prefix: /

CCDNUserProfileBundle:
    resource: "@CCDNUserProfileBundle/Resources/config/routing.yml"
    prefix: /

CCDNUserAdminBundle:
    resource: "@CCDNUserAdminBundle/Resources/config/routing.yml"
    prefix: /

CCDNUserUserBundle:
    resource: "@CCDNUserUserBundle/Resources/config/routing.yml"
    prefix: /

CCDNUserSecurityBundle:
    resource: "@CCDNUserSecurityBundle/Resources/config/routing.yml"
    prefix: /

# CCDNForum bundles
CCDNForumAdminBundle:
    resource: "@CCDNForumAdminBundle/Resources/config/routing.yml"
    prefix: /

ccdn_forum_forum_home_root:
    pattern: /
    defaults: { _controller: CCDNForumForumBundle:Category:index, _locale: en }


CCDNForumForumBundle:
    resource: "@CCDNForumForumBundle/Resources/config/routing.yml"
    prefix: /

CCDNForumKarmaBundle:
    resource: "@CCDNForumKarmaBundle/Resources/config/routing.yml"
    prefix: /
    
# CCDNMessage bundles
CCDNMessageMessageBundle:
    resource: "@CCDNMessageMessageBundle/Resources/config/routing.yml"
    prefix:   /
    