# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

forum:
    resource: "@CCDNForumBundle/Resources/config/routing.yml"
    resource: "@CCDNForumAdminBundle/Resources/config/routing.yml"
    resource: "@CCDNForumModeratorBundle/Resources/config/routing.yml"

member:
    resource: "@CCDNUserMemberBundle/Resources/config/routing.yml"
profile:
    resource: "@CCDNUserProfileBundle/Resources/config/routing.yml"
user_admin:
    resource: "@CCDNUserUserAdminBundle/Resources/config/routing.yml"
user:
    resource: "@CCDNUserUserBundle/Resources/config/routing.yml"