# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

#forum:
#    resource: "@CCDNForumBundle/Resources/config/routing.yml"
#    resource: "@CCDNForumAdminBundle/Resources/config/routing.yml"
#    resource: "@CCDNForumModeratorBundle/Resources/config/routing.yml"
CCDNForumModeratorBundle:
    resource: "@CCDNForumModeratorBundle/Resources/config/routing.yml"
    prefix: /

CCDNForumAdminBundle:
    resource: "@CCDNForumAdminBundle/Resources/config/routing.yml"
    prefix: /

CCDNForumForumBundle:
    resource: "@CCDNForumForumBundle/Resources/config/routing.yml"
    prefix: /

member:
    resource: "@CCDNUserMemberBundle/Resources/config/routing.yml"
profile:
    resource: "@CCDNUserProfileBundle/Resources/config/routing.yml"
user_admin:
    resource: "@CCDNUserUserAdminBundle/Resources/config/routing.yml"
user:
    resource: "@CCDNUserUserBundle/Resources/config/routing.yml"

message:
    resource: "@CCDNMessageMessageBundle/Resources/config/routing.yml"

_security_check:
      pattern:  /login_check/
_security_logout:
    pattern:  /logout