# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

ccdn_homepage:
    pattern: /
    defaults: { _controller: CCDNForumForumBundle:Category:index, _locale: en }

#####################################
#
#    User Routing.
#
#####################################
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

CCDNUserUserBundle:
    resource: "@CCDNUserUserBundle/Resources/config/routing.yml"


#####################################
#
#    Other User Resources Routing.
#
#####################################
CCDNUserSecurityBundle:
    resource: "@CCDNUserSecurityBundle/Resources/config/routing.yml"

CCDNUserProfileBundle:
    resource: "@CCDNUserProfileBundle/Resources/config/routing.yml"

CCDNUserMemberBundle:
    resource: "@CCDNUserMemberBundle/Resources/config/routing.yml"

CCDNUserAdminBundle:
    resource: "@CCDNUserAdminBundle/Resources/config/routing.yml"

#####################################
#
#    Component Routing.
#
#####################################

CCDNComponentAttachmentBundle:
    resource: "@CCDNComponentAttachmentBundle/Resources/config/routing.yml"

CCDNComponentDashboardBundle:
    resource: "@CCDNComponentDashboardBundle/Resources/config/routing.yml"

#####################################
#
#    Forum Routing.
#
#####################################
#CCDNForumForumBundle:
#    resource: "@CCDNForumForumBundle/Resources/config/routing.yml"

CCDNForumForumBundle-Admin:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin.yml"
    prefix: /{_locale}/forum/admin

CCDNForumForumBundle-Admin-Forum:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-forum.yml"
    prefix: /{_locale}/forum/admin/manage-forums

CCDNForumForumBundle-Admin-Category:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-category.yml"
    prefix: /{_locale}/forum/admin/manage-categories

CCDNForumForumBundle-Admin-Board:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-board.yml"
    prefix: /{_locale}/forum/admin/manage-boards

CCDNForumForumBundle-Admin-Topic:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-topic.yml"
    prefix: /{_locale}/forum/admin/manage-topics

CCDNForumForumBundle-Admin-Post:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-post.yml"
    prefix: /{_locale}/forum/admin/manage-posts



CCDNForumForumBundle-Moderator-Topic:
    resource: "@CCDNForumForumBundle/Resources/config/routing/moderator-topic.yml"
    prefix: /{_locale}/forum/moderator/manage-topics

CCDNForumForumBundle-Moderator-Post:
    resource: "@CCDNForumForumBundle/Resources/config/routing/moderator-post.yml"
    prefix: /{_locale}/forum/moderator/manage-posts



CCDNForumForumBundle-User-Category:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-category.yml"
    prefix: /{_locale}/forum/category

CCDNForumForumBundle-User-Board:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-board.yml"
    prefix: /{_locale}/forum/board

CCDNForumForumBundle-User-Topic:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-topic.yml"
    prefix: /{_locale}/forum/topic

CCDNForumForumBundle-User-Post:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-post.yml"
    prefix: /{_locale}/forum/post

CCDNForumForumBundle-User-Draft:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-draft.yml"
    prefix: /{_locale}/forum/draft

CCDNForumForumBundle-User-Subscription:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-subscription.yml"
    prefix: /{_locale}/forum/subscription

#CCDNForumAdminBundle:
#    resource: "@CCDNForumAdminBundle/Resources/config/routing.yml"

#####################################
#
#    Message Routing.
#
#####################################
CCDNMessageMessageBundle:
    resource: "@CCDNMessageMessageBundle/Resources/config/routing.yml"
