security:
        
    access_decision_manager:
        strategy: unanimous
        
    encoders:
        "FOS\UserBundle\Model\UserInterface":
            algorithm: sha512
            encode_as_base64: false
            iterations: 1
    #    Symfony\Component\Security\Core\User\User: plaintext


    providers:
        #in_memory:
        #    users:
        #        user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #        admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_manager
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        main:
            pattern: ^/.*
#            fos_facebook:
#                app_url: "http://apps.facebook.com/%facebook_app_id%/"
#                server_url: "http://%server_host%/facebookApp"
#                login_path: /login
#                check_path: /login_check
#                default_target_path: /
#                provider:       my_fos_facebook_provider
#            logout:
#                handlers: ["fos_facebook.logout_handler"]
            anonymous:  true
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                success_handler: ccdn_user_security.component.authentication.handler.login_success_handler
                failure_handler: ccdn_user_security.component.authentication.handler.login_failure_handler
                failure_path:   null
            logout:
                path:   /logout
                success_handler: ccdn_user_security.component.authentication.handler.logout_success_handler
#               target: /
            remember_me:
                key:    "%secret%"
                lifetime: 604800
                
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

    role_hierarchy:
        ROLE_USER:          ROLE_USER
        ROLE_MODERATOR:     [ROLE_USER]
        ROLE_ADMIN:         [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN]

