jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_decision_manager:
        strategy: unanimous

    #encoders:
    #    Symfony\Component\Security\Core\User\User: plaintext

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        fos_userbundle:
            #id: fos_user.user_manager
            id: fos_user.user_provider.username_email
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            switch_user: true
            pattern: ^/
            form_login:
                provider:        fos_userbundle
                login_path:      /login
                use_forward:     false
                check_path:      /login_check
                #success_handler: ccdn_user_security.component.authentication.handler.login_success_handler
                #failure_handler: ccdn_user_security.component.authentication.handler.login_failure_handler
                failure_path:    null
                csrf_provider:   form.csrf_provider
                #success_handler:
            logout:
                path: /logout
                target: /
                #success_handler: ccdn_user_security.component.authentication.handler.logout_success_handler
            anonymous: true
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
