parameters:

    sub_ccdn_forum_forum.component.bb_code.acl_integrator.class: SubCCDNForum\ForumBundle\Component\BBCode\TagACLIntegrator

services:

    sub_ccdn_forum_forum.component.bb_code.acl_integrator:
        class: %sub_ccdn_forum_forum.component.bb_code.acl_integrator.class%
        arguments:
            - %sub_ccdn_forum_forum.bb_parser.acl%
        tags:
            - { name: ccdn_component_bb_code.acl }