ccdn_component_common:
    service:
        provider:
            profile_provider:
                class: CCDNUser\ProfileBundle\Component\Provider\Profile\ProfileProvider
    header:
        brand:
            route: ccdn_homepage
            label: Code Consortium
