ccdn_forum_forum:
    form:
        type:
            post_create:
                class: SubCCDNForum\ForumBundle\Form\Type\PostCreateFormType
            post_update:
                class: SubCCDNForum\ForumBundle\Form\Type\PostUpdateFormType
