ccdn_message_message:
    entity:
        user:
            class: CCDNUser\UserBundle\Entity\User
    form:
        type:
            message:
                class: SubCCDNMessage\MessageBundle\Form\Type\MessageFormType
