ccdn_user_profile:
    template:
        engine:                                twig
        pager_theme:                          CCDNUserProfileBundle:Common:Paginator/twitter_bootstrap.html.twig
    entity:
        user:
            class:                            CCDNUser\UserBundle\Entity\User
    seo:
        title_length:                         67
    member:
        list:
            layout_template:                  CCDNComponentCommonBundle::Layout/base_single_column.html.twig
            members_per_page:                 50
            member_since_datetime_format:     d-m-Y - H:i
            requires_login:                   false
    profile:
        fallback_avatar:                      /bundles/ccdnuserprofile/img/avatar_anonymous.gif
        edit:
            personal:
                layout_template:              CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
                form_theme:                   CCDNUserProfileBundle:Common:Form/fields.html.twig
            info:
                layout_template:              CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
                form_theme:                   CCDNUserProfileBundle:Common:Form/fields.html.twig
            contact:
                layout_template:              CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
                form_theme:                   CCDNUserProfileBundle:Common:Form/fields.html.twig
            avatar:
                layout_template:              CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
                form_theme:                   CCDNUserProfileBundle:Common:Form/fields.html.twig
            bio:
                layout_template:              CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
                form_theme:                   CCDNUserProfileBundle:Common:Form/fields.html.twig
            signature:
                layout_template:              CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
                form_theme:                   CCDNUserProfileBundle:Common:Form/fields.html.twig
        show:
            requires_login:                   false
            overview:
                layout_template:              CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
                member_since_datetime_format: d-m-Y - H:i
                last_login_datetime_format:   d-m-Y - H:i
            bio:
                layout_template:              CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
