ccdn_user_security:   
    route_referer:        
        route_ignore_list: []
    login_shield:         
        enable_shield: true 
        block_for_minutes: 10 
        limit_failed_login_attempts:  
            before_recover_account: 15
            before_return_http_500: 25 
        primary_login_route:
            name:                 fos_user_security_login 
            params:               []
        recover_account_route:  
            name:                 fos_user_resetting_request 
            params:               []
        block_routes_when_denied: []
