ccdn_user_security:
    entity:
        user:
            class: CCDNUser\UserBundle\Entity\User
    route_referer:
        enabled: true
        route_ignore_list:
            - fos_user_security_login
            - fos_user_security_check
            - fos_user_security_logout
            - fos_user_registration_register
            - fos_user_registration_check_email
            - fos_user_registration_confirm
            - fos_user_registration_confirmed
            - fos_user_resetting_request
            - fos_user_resetting_send_email
            - fos_user_resetting_check_email
            - fos_user_resetting_reset
            - fos_user_change_password
    login_shield:
        route_login:
            name:                  fos_user_security_login
            params:                []
        force_account_recovery:    # Specify all routes to block after attempt limit is reached, and account recovery route to force browser redirect.
            enabled:               true
            after_attempts:        2
            duration_in_minutes:   2
            route_recover_account:
                name:              fos_user_resetting_request
                params:            []
            routes:
                - fos_user_security_login
                - fos_user_security_check
                - fos_user_security_logout
        block_pages:               # Specify all routes to block after attempt limit is reached.
            enabled:               true
            after_attempts:        4
            duration_in_minutes:   2
            routes:
                - fos_user_security_login
                - fos_user_security_check
                - fos_user_security_logout
                - fos_user_registration_register
                - fos_user_registration_check_email
                - fos_user_registration_confirm
                - fos_user_registration_confirmed
                - fos_user_resetting_request
                - fos_user_resetting_send_email
