ccdn_user_admin:
    template:
        engine:                            twig
        pager_theme:                       CCDNUserAdminBundle:Common:Paginator/twitter_bootstrap.html.twig
    users_per_page:                        30
    entity:
        user:
            class:                         CCDNUser\UserBundle\Entity\User
    seo:
        title_length:                      67
    account:
        show_newest_users:
            layout_template:               CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
            member_since_datetime_format:  d-m-Y - H:i
        show_user:
            layout_template:               CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
            member_since_datetime_format:  d-m-Y - H:i
        edit_user_account:
            layout_template:               CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
            form_theme:                    CCDNUserAdminBundle:Common:Form/fields.html.twig
    ban:
        show_banned_users:
            layout_template:               CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
            member_since_datetime_format:  d-m-Y - H:i
    activation:
        show_unactivated_users:
            layout_template:               CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
            member_since_datetime_format:  d-m-Y - H:i
    role:
        set_users_role:
            layout_template:               CCDNComponentCommonBundle::Layout/base_sidebar_left.html.twig
            form_theme:                    CCDNUserAdminBundle:Common:Form/fields.html.twig
